name: Windows – Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Download Downloads.bat
        run: Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"

      - name: Run Downloads.bat
        run: cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
